In [2]:
# Import TF and TF Hub libraries.
import tensorflow as tf
import tensorflow_hub as hub

In [ ]:


# Load the input image.
image_path = r"C:/Users/User/Desktop/General_fold/Thesis code/HHP-Net-Private/HHP-Net-Private/imgs/1.png"
image = tf.io.read_file(image_path)
image = tf.compat.v1.image.decode_jpeg(image)
image = tf.expand_dims(image, axis=0)
# Resize and pad the image to keep the aspect ratio and fit the expected size.
image = tf.cast(tf.image.resize_with_pad(image, 256, 256), dtype=tf.int32)


# Download the model from TF Hub.
model = hub.load("https://www.kaggle.com/models/google/movenet/TensorFlow2/singlepose-thunder/4")
movenet = model.signatures['serving_default']

# Run model inference.
outputs = movenet(image)
# Output is a [1, 1, 17, 3] tensor.
keypoints = outputs['output_0']


In [6]:
outputs

{'output_0': <tf.Tensor: shape=(1, 1, 17, 3), dtype=float32, numpy=
 array([[[[0.49302933, 0.5994846 , 0.6164533 ],
          [0.46903756, 0.63503706, 0.41868463],
          [0.46657345, 0.5952576 , 0.5128882 ],
          [0.491509  , 0.7108746 , 0.8258268 ],
          [0.4779667 , 0.61397547, 0.27380136],
          [0.67533416, 0.798098  , 0.6793044 ],
          [0.6672993 , 0.5713731 , 0.71447814],
          [0.91747344, 0.8059572 , 0.09377122],
          [0.8944976 , 0.5486443 , 0.19038695],
          [0.8020529 , 0.20210654, 0.12887429],
          [0.8040167 , 0.1986379 , 0.06331864],
          [1.0140074 , 0.71402174, 0.09071886],
          [1.0045652 , 0.5858158 , 0.11480135],
          [0.9148049 , 0.8453067 , 0.03222585],
          [0.6793179 , 0.5727484 , 0.00900854],
          [0.9845637 , 0.961337  , 0.03076796],
          [0.95929056, 0.99537146, 0.02826555]]]], dtype=float32)>}

In [5]:
keypoints

<tf.Tensor: shape=(1, 1, 17, 3), dtype=float32, numpy=
array([[[[0.49302933, 0.5994846 , 0.6164533 ],
         [0.46903756, 0.63503706, 0.41868463],
         [0.46657345, 0.5952576 , 0.5128882 ],
         [0.491509  , 0.7108746 , 0.8258268 ],
         [0.4779667 , 0.61397547, 0.27380136],
         [0.67533416, 0.798098  , 0.6793044 ],
         [0.6672993 , 0.5713731 , 0.71447814],
         [0.91747344, 0.8059572 , 0.09377122],
         [0.8944976 , 0.5486443 , 0.19038695],
         [0.8020529 , 0.20210654, 0.12887429],
         [0.8040167 , 0.1986379 , 0.06331864],
         [1.0140074 , 0.71402174, 0.09071886],
         [1.0045652 , 0.5858158 , 0.11480135],
         [0.9148049 , 0.8453067 , 0.03222585],
         [0.6793179 , 0.5727484 , 0.00900854],
         [0.9845637 , 0.961337  , 0.03076796],
         [0.95929056, 0.99537146, 0.02826555]]]], dtype=float32)>